name: $(BuildId)

trigger:
  batch: false
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
  ARTIFACT_NAME: drop

stages:
- stage: build
  jobs:
  - job: RunTests
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --output ./bin
        fi
      displayName: 'build function extensions'
    - script: npm install
      displayName: 'npm install'
    - script: npm run lint
      displayName: 'npm run lint'
    - script: npm run test-with-coverage
      displayName: 'npm run test-with-coverage'
    - script: npm prune --production
      displayName: 'npm prune --production'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
        testRunner: JUnit
    - task: ArchiveFiles@2
      displayName: 'Archive Function App'
      inputs:
        archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
        includeRootFolder: false
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        artifactName: $(ARTIFACT_NAME)
        pathtoPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'

- stage: deployReviewEnvironment
  displayName: 'Deploy to Review Environment'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull/'), eq(variables['Build.Reason'], 'PullRequest'))
  dependsOn: build
  jobs:
  - template: ./templates/deployment-job.yml
    parameters:
      appName: 'nhsuk-cache-flush-func-dev-uks-PR-$(system.pullRequest.pullRequestNumber)'
      appTest: deployed
      azureSubscription: Development
      environment: cacheflush-review
      releaseEnvironment: dev

- stage: testingMerging
  displayName: 'testing merging and deleting review envs'
  jobs:
  - job: deleteReviewEnvironment
    displayName: Delete review environment for merged PR
    steps:
    - bash: echo env
      displayName: 'echo env'

- stage: deployIntegrationEnvironment
  displayName: 'Deploy to Integration Environment'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build
  jobs:
  # - job: deleteReviewEnvironment
  #   displayName: Delete review environment for merged PR
  #   steps:
  #   - bash: echo env
  #     displayName: 'echo env'
    # - task: AzureCLI@2
    #   displayName: 'delete review environment for merged PR'
    #   inputs:
    #     azureSubscription: Development
    #     inlineScript: |
    #       az  functionapp delete --name
    #     scriptLocation: inlineScript
    #     scriptType: bash
  - template: ./templates/deployment-job.yml
    parameters:
      appName: 'nhsuk-cache-flush-func-int-uks'
      appTest: running
      azureSubscription: 'www.nhs.uk'
      environment: cacheflush-int
      releaseEnvironment: int

- stage: deployStagingEnvironment
  displayName: 'Deploy to Staging Environment'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  dependsOn: build
  jobs:
  - template: ./templates/deployment-job.yml
    parameters:
      appName: 'nhsuk-cache-flush-func-stag-uks'
      appTest: running
      azureSubscription: 'www.nhs.uk'
      environment: cacheflush-staging
      releaseEnvironment: staging

- stage: deployProductionEnvironment
  displayName: 'Deploy to Production Environment'
  dependsOn: deployStagingEnvironment
  jobs:
  - template: ./templates/deployment-job.yml
    parameters:
      appName: 'nhsuk-cache-flush-func-prod-uks'
      appTest: running
      azureSubscription: 'www.nhs.uk'
      environment: cacheflush-production
      releaseEnvironment: production
