name: $(BuildId)

trigger:
  batch: false
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

stages:
- stage: test
  jobs:
  - job: Test
    steps:
    - bash: |
        echo "This is running a bash script inside devops"
      displayName: 'bash script'
    - task: AzureCLI@2
      inputs:
        azureSubscription: Development
        addSpnToEnvironment: true
        inlineScript: |
          # List accounts that this user is logged in to
          az account list

          echo "this is the service principal ID used to connect to azure"
          echo $servicePrincipalId
        scriptLocation: inlineScript
        scriptType: bash
